const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.gamepad,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTapGesture
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Wall: 0},
	{TileMovement: 0},
	{Player: 0},
	{TimeCounter: 0},
	{Range: 0},
	{Flash: 0},
	{Timer: 0},
	{Bomb: 0},
	{Keyboard: 0},
	{hp: 0},
	{hpMax: 0},
	{Damaged: 0},
	{Tween: 0},
	{Pin: 0},
	{BreakableWall: 0},
	{Ground: 0},
	{Direction: 0},
	{Enemy: 0},
	{Flame: 0},
	{Dust: 0},
	{Gamepad: 0},
	{Fade: 0},
	{TextFont: 0},
	{TextBackground: 0},
	{Text: 0},
	{e: 0},
	{MoveTo: 0},
	{CoinUI: 0},
	{Level: 0},
	{Audio: 0},
	{Coin: 0},
	{TimerBar: 0},
	{damaged: 0},
	{hpBG: 0},
	{ownerUID: 0},
	{HpBarFill: 0},
	{Sprite: 0},
	{moveLeft: 0},
	{Touch: 0},
	{moveRight: 0},
	{moveUp: 0},
	{moveDown: 0},
	{Sprite2: 0},
	{BombUI: 0},
	{placeBomb: 0},
	{Browser: 0},
	{tokens: 0},
	{hurryPlayed: 0},
	{ExplosionRange: 0},
	{XOffset: 0},
	{YOffset: 0}
];

self.InstanceType = {
	Wall: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BreakableWall: class extends self.ISpriteInstance {},
	Ground: class extends self.ITilemapInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Flame: class extends self.ISpriteInstance {},
	Dust: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	TextBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	e: class extends self.ITextInstance {},
	CoinUI: class extends self.ISpriteInstance {},
	Level: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Coin: class extends self.ISpriteInstance {},
	TimerBar: class extends self.ISpriteInstance {},
	hpBG: class extends self.ISpriteInstance {},
	HpBarFill: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	moveLeft: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	moveRight: class extends self.ISpriteInstance {},
	moveUp: class extends self.ISpriteInstance {},
	moveDown: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	BombUI: class extends self.ISpriteInstance {},
	placeBomb: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}